spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_PROD_HOST}:${POSTGRES_PROD_PORT:5432}/${POSTGRES_PROD_DBNAME}
    username: ${POSTGRES_PROD_USERNAME}
    password: ${POSTGRES_PROD_PASSWORD}

  session:
    cookie:
      same-site: none
      secure: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public

    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

clova:
  api:
    url: ${CLOVA_API_URL}
    key: ${CLOVA_API_KEY}
    request-id: ${CLOVA_REQUEST_ID}

oauth2:
  success-url: ${OAUTH2_SUCCESS_URL}

logging:
  level:
    org.hibernate.SQL: warn