spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_DEV_HOST}:${POSTGRES_DEV_PORT:5432}/${POSTGRES_DEV_DBNAME}
    username: ${POSTGRES_DEV_USERNAME}
    password: ${POSTGRES_DEV_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: debug